### ISSUE TITLE
CodaLab could not download Docker Image.

### ISSUE THREAD

**Issue by combacsa** [rajpurkar/SQuAD-explorer#11]
First of all, thank you for your efforts maintaining SQuAD.

It seems that CodaLab fails to download Docker Image for official SQuAD evaluation scripts. Could you please check the status of the Docker image?

**Comment by combacsa** [comment]
Hello, any updates on this? Can you please close the issue if it is resolved? Thanks.

**Comment by robinjia** [comment]
We believe this was related to https://github.com/codalab/codalab-worksheets/issues/2066 which seems to be fixed now, please try again and follow-up on that issue if it doesn't work.
