### ISSUE TITLE
what is the annotation tool to create question and answer?

### ISSUE THREAD

**Issue by kenyeung128** [rajpurkar/SQuAD-explorer#2]
Hi, what is the annotation tool to create question and answer? so it could create the answer with the span start and end position? seems i couldn't find any info on that. thanks

**Comment by rajpurkar** [comment]
We haven't released the code for annotations yet

**Comment by kenyeung128** [comment]
Hi @rajpurkar would it be possible to release the code for annotations? thanks

**Comment by rajpurkar** [comment]
We won't release it at least for the next few months, sorry!

**Comment by kenyeung128** [comment]
thanks

**Comment by vitojph** [comment]
Hi! Any news on this? Are you planning to release the annotation tool? Thanks!

**Comment by guillim** [comment]
Same question here! I would really like to see your annotation tool to create question and answer!!! @rajpurkar

**Comment by jvence** [comment]
Any update on this?

**Comment by guillim** [comment]
Since no answer was provided, and as we wanted to build a QA dataset for the french language, we built a new annotation tool. Feel free to use it and open PR if necessary => https://github.com/etalab/piaf/

**Comment by vitojph** [comment]
Thanks a lot @guillim. It's so useful and it looks great 👏
