### ISSUE TITLE
How do I use this tool to visualize my own result?

### ISSUE THREAD

**Issue by guotong1988** [rajpurkar/SQuAD-explorer#3]
https://github.com/rajpurkar/SQuAD-explorer/tree/gh-pages
Thank you..
Or Do you know some other code to visualize the results?

**Comment by rajpurkar** [comment]
Just plug in your prediction file here:
https://github.com/rajpurkar/SQuAD-explorer/tree/master/models

To run a local version of the website:
- run setup.sh
- run gulp

**Comment by tonytu16** [comment]
Hello,

Should I expect to see a local host address after I run the command 'gulp'?

Thanks
