### ISSUE TITLE
Evaluation results are missing in out-v1.1.json

### ISSUE THREAD

**Issue by intfloat** [rajpurkar/SQuAD-explorer#4]
Hi, @rajpurkar @robinjia 

In the file out-v1.1.json of master branch, I notice that two bundles [0x3252d4eb0a98413d8a41d47194273184](https://github.com/rajpurkar/SQuAD-explorer/blob/master/out-v1.1.json#L14222) and [0xf01b48802be74ffaafb123df13063c51](https://github.com/rajpurkar/SQuAD-explorer/blob/master/out-v1.1.json#L13740) actually finished running successfully but the scores are null.

The result for the bundle 0x3252d4eb0a98413d8a41d47194273184 is 
`{"f1":89.22391504017472, "exact_match": 83.12178747508653}` 
as shown in https://worksheets.codalab.org/bundles/0x3252d4eb0a98413d8a41d47194273184/; 

And the result for the bundle 0xf01b48802be74ffaafb123df13063c51 is
`{"f1":89.79569137609076, "exact_match": 83.98195741109829}` 
as shown in https://worksheets.codalab.org/bundles/0xf01b48802be74ffaafb123df13063c51/ ;

Can you please take a minute and fix this issue?

Thanks.

**Comment by rajpurkar** [comment]
Is this still a problem?

**Comment by intfloat** [comment]
I am afraid it still is. Scores for these two bundles are not displayed on SQuAD 1.1 leaderboard.

**Comment by intfloat** [comment]
Problem solved, thanks!
